Added "fast forward"
ping-payments/ping_csharp_sdk pull request #25
Opened 2022-07-26 09:25 UTC by LJsson

added fast forward functionality and some tests regarding status management of payment orders

2022-07-26 11:05 UTC, gustavFransson commented on PingPayments.PaymentsApi.Tests/V1/PaymentOrderResourceTests.cs
> +
Du gör detta, extakt samma på tre ställen. Går det att bryta ut den tror du?

2022-08-25 08:47 UTC, norrbacka requested changes
Snyggt, bra med tester!

Jag tror OpenOrderId är onödigt - se kommentar. Så den borde vi nog ta bort. Om jag inte missuppfattat något förstås :)

2022-08-25 08:47 UTC, norrbacka commented on PingPayments.PaymentsApi.Tests/V1/PaymentOrderResourceTests.cs
> +            AssertHttpApiError(await _api.PaymentOrder.V1.Split(TestData.OpenOrderId));
Kanske går att skriva utan OpenOrderId, och istället bara göra en ny order? T

2022-08-25 08:59 UTC, LJsson commented on PingPayments.PaymentsApi.Tests/V1/PaymentOrderResourceTests.cs
> +            AssertHttpApiError(await _api.PaymentOrder.V1.Split(TestData.OpenOrderId));
Yes jag tänkte nog att man kunde slippa skapa massa nya ordrar och betalningar varje gång när jag gjorde detta. Men det kanske är bättre ändå än "onödiga id:n"

2022-09-01 11:37 UTC, merged